os: linux
language: python
dist: bionic

jobs:
  include:
    # The pypy tests are slow, so we list them first
    - python: pypy3.6-7.2.0
    - language: generic
      env: PYPY_NIGHTLY_BRANCH=py3.6
    # Qemu tests are also slow
    # The unique thing this provides is testing on the given distro's
    # kernel, which is important when we use new kernel features. This
    # is also good for testing the latest openssl etc., and getting
    # early warning of any issues that might happen in the next Ubuntu
    # LTS.
    - language: generic
      # We use bionic for the host, b/c rumor says that Travis's
      # 'bionic' systems have nested KVM enabled.
      dist: bionic
      env:
        - "JOB_NAME='Ubuntu 19.10, full VM'"
        - "VM_IMAGE=https://cloud-images.ubuntu.com/eoan/current/eoan-server-cloudimg-amd64.img"
    - python: 3.6-dev
    - python: 3.7-dev
    - python: 3.8-dev
    - python: nightly

script:
  - ./ci.sh

branches:
  except:
    - /^dependabot/.*/
