jobs:

- job: 'macOS'
  pool:
    vmImage: 'macOS-latest'
  timeoutInMinutes: 10
  strategy:
    matrix:
      "Python 3.5":
        python.version: '3.5'
      "Python 3.6":
        python.version: '3.6'
      "Python 3.7":
        python.version: '3.7'
      "Python 3.8":
        python.version: '3.8'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - bash: ./ci.sh
    displayName: "Run the actual tests"
